GET http://localhost:3001/api/persons/

###
POST http://localhost:3001/api/persons/ 
content-type: application/json

{
    "name": "Malenucha",
    "number": "234324534523452345"
}

###
DELETE http://localhost:3001/api/persons/2 HTTP/1.1
#content-type: application/json

